# Generated by Django 2.0 on 2018-01-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('fName', models.CharField(max_length=25)),
                ('lName', models.CharField(max_length=25)),
                ('cec', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('location', models.CharField(choices=[('RTP', 'RTP'), ('Mexico', 'Mexico'), ('Krakow', 'Krakow')], max_length=6)),
            ],
        ),
    ]
