# Generated by Django 2.0 on 2018-01-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='location',
            field=models.CharField(choices=[('San Jose', 'San Jose'), ('RTP', 'RTP'), ('Mexico', 'Mexico'), ('Krakow', 'Krakow')], max_length=8),
        ),
    ]
