# Generated by Django 2.0 on 2018-02-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20180129_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cohort',
            field=models.CharField(blank=True, choices=[('Spring 2018', 'Spring 2018')], max_length=20, null=True),
        ),
    ]
