# Generated by Django 2.0 on 2018-02-13 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_auto_20180213_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='cohort',
        ),
    ]
