# Generated by Django 2.0 on 2018-02-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_remove_member_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cohort',
            field=models.CharField(choices=[('Spring 2018', 'Spring 2018')], default=None, max_length=20),
        ),
    ]
