# Generated by Django 2.0 on 2018-02-14 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_member_cohort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('cec', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('fname', models.CharField(blank=True, max_length=25, null=True)),
                ('lname', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('tname', models.CharField(blank=True, max_length=50, null=True)),
                ('cohort', models.CharField(blank=True, max_length=20, null=True)),
                ('business_case', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Team'),
        ),
    ]
