# Generated by Django 2.0.1 on 2018-01-25 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judgeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=25)),
                ('lName', models.CharField(max_length=25)),
                ('choices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judgeapp.Timeslot')),
            ],
        ),
    ]
