# Generated by Django 2.0.1 on 2018-01-25 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judgeapp', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='choices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='judgeapp.Timeslot'),
        ),
    ]
