# Generated by Django 2.0.1 on 2018-01-26 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judgeapp', '0003_auto_20180125_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='choices',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='judgeapp.User'),
        ),
    ]
