# Generated by Django 2.0.1 on 2018-03-05 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judgeapp', '0004_auto_20180126_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='user',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
